spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    password: 123456
    username: root
  jpa:
    show-sql: true